dist: bionic
language: python
python:
  - '3.6'

install:
  - pip install -r tests/test_requirements.txt

  # Install CBC solver
  - sudo apt-get install coinor-cbc

  # Install specific branch of oemof
  - git clone https://github.com/oemof/oemof.git
  - cd oemof
  - git fetch origin pull/592/head:smoothbranch
  - git checkout smoothbranch
  - pip install .
  - cd ..

  # Install other smooth dependencies
  - pip install -r requirements.txt

  # Build docs
  - pip install -r doc/requirements.txt
  - make -C doc html

script:
  # Run pytest in `tests` directory
  - pytest tests

  #TODO re-enable flake8
  #- flake8
